[tasks.clean-cargo]
cwd = "/src/fuzzer"
script = """
cargo clean
"""

[tasks.clean-fuzzer]
cwd = "/src/fuzzer"
script = """
rm -f fuzzer || true
"""

[tasks.clean-evmone]
cwd = "/src/third-party/evmone"
script = """
find . -name 'CMakeCache.txt' -delete
rm -rf build/ || true
"""

[tasks.clean-geth]
cwd = "/src/geth"
script = """
rm -f libgoexecute.h libgoexecute.so || true
"""

[tasks.clean]
dependencies = ["clean-cargo", "clean-fuzzer", "clean-evmone", "clean-geth"]

[tasks.build-compilers]
script = """
cargo build
"""

[tasks.build-evmone]
cwd = "/src/third-party/evmone"
script = """
cmake -S . -B build -DCMAKE_THREAD_LIBS_INIT="-lpthread" -DCMAKE_HAVE_THREADS_LIBRARY=1 -DCMAKE_USE_WIN32_THREADS_INIT=0 -DCMAKE_USE_PTHREADS_INIT=1 -DTHREADS_PREFER_PTHREAD_FLAG=ON -DBUILD_SHARED_LIBS=OFF -DCMAKE_C_COMPILER=/src/fuzzer/target/debug/libafl_cc -DCMAKE_CXX_COMPILER=/src/fuzzer/target/debug/libafl_cxx
cmake --build build --parallel
"""

[tasks.build-silkworm]
cwd = "/src/third-party/silkworm"
script = """
cmake -S . -B build -DCMAKE_C_COMPILER=/src/fuzzer/target/debug/libafl_cc -DCMAKE_CXX_COMPILER=/src/fuzzer/target/debug/libafl_cxx -DCMAKE_C_FLAGS="-shared" -DCMAKE_SHARED_LIBRARY_SUFFIX=".so" -DSILKWORM_CORE_ONLY=ON
cmake --build build --parallel
"""

[tasks.clean-silkworm]
cwd = "/src/third-party/silkworm"
script = """
find . -name 'CMakeCache.txt' -delete
rm -rf build/ || true
"""

[tasks.build-geth]
cwd = "/src/geth"
script = """
go build -o libgeth.so -buildmode=c-shared geth.go
"""

# TODO: Update evmone and evmc to silkroad/third-party/.. 
[tasks.build-fuzzer]
cwd = "/src/third-party/evmone"
script = """
/src/fuzzer/target/debug/libafl_cxx \
-std=c++20 \
-I $(pwd)/include \
-I $(pwd)/lib \
-I $(pwd)/evmc/include \
-I /src/third-party/intx/include/ \
-I /src/third-party/ethash/include \
-I /src/third-party/silkworm \
-I /src/third-party/expected/include \
-I /src/hird-party/silkworm/third_party/silkpre \
-I /src/third-party/GSL/include \
-I /src/third-party/abseil-cpp/ \
-I /src/third-party/json/include \ 
-o /src/fuzzer/fuzzer \
/src/geth/libgeth.so \
/src/silkworm/harness.cpp \
/src/third-party/silkworm/build/silkworm/core/libsilkworm_core.a \
-lm -ldl -lpthread -lstdc++ -lgcc -lutil -lrt
"""

[tasks.geth-routine]
dependencies = ["build-geth", "build-fuzzer"]

[tasks.evmone-routine]
dependencies = ["build-compilers", "build-geth", "clean-evmone", "build-evmone", "build-fuzzer"]

[tasks.silkworm-routine]
dependencies = ["build-compilers", "build-geth", "build-fuzzer"]

[tasks.build]
dependencies = ["build-compilers", "build-geth", "build-evmone", "build-fuzzer"]

[tasks.rebuild]
dependencies = ["clean", "build"]
