include(hunter_cmake_args)

hunter_config(
  ethash
  VERSION 0.9.0
  CMAKE_ARGS 
    ETHASH_BUILD_ETHASH=ON 
    ETHASH_BUILD_GLOBAL_CONTEXT=OFF 
    ETHASH_BUILD_TESTS=OFF
    CMAKE_POSITION_INDEPENDENT_CODE=ON
)

hunter_config(
  abseil
  VERSION ${HUNTER_abseil_VERSION}
  CMAKE_ARGS
  # ABSL_PROPAGATE_CXX_STD=ON
  # ABSL_ENABLE_INSTALL=OFF
  # ABSL_RUN_TESTS=OFF
    CMAKE_POSITION_INDEPENDENT_CODE=ON
)
